spring:
  data:
    mongodb:
      database: eportfolio
      host: localhost
      port: 27017
      auto-index-creation: true

jwt:
  secret: thisVichyssoiseOfVerbiageVeersMostVerbose000000thisVichyssoiseOfVerbiageVeersMostVerbose
  expiration: 624000
  tokenHeader: Authorization
  tokenHead: Bearer

oauth:
  google:
    redirectURL: http://localhost:5000/oauth/google
    clientId: 413929433417-f5ji4dr4tf36e3q4agbrol5n7buaslhl.apps.googleusercontent.com
    clientSecret: 1he96IBDy9ip8InllMsqVbes