spring:
  data:
    mongodb:
      database: eportfolio
      host: localhost
      port: 27017
      auto-index-creation: true

jwt:
  secret: thisVichyssoiseOfVerbiageVeersMostVerbose000000thisVichyssoiseOfVerbiageVeersMostVerbose
  expiration: 624000
  tokenHeader: Authorization
  tokenHead: Bearer