spring:
  data:
    mongodb:
      authentication-database: admin
      database: eportfolio
      username: root
      password: 123456
      host: localhost
      port: 27017
      auto-index-creation: true